/* ---------------------------------------------------------------------------
   Morph target blending.

   Every shape change starts here: the sculpted MakeHuman targets are added to
   the rest cage with the weights the sliders ask for. Each target is a sparse
   list of moved vertices, so a slider that only touches the calves costs a few
   hundred adds.

   Nothing in this file is generated by formula. Every offset was sculpted by a
   person, which is why the surface keeps skin folds, tendon dips and the small
   left-right differences that make a body read as real.
   --------------------------------------------------------------------------- */

export class MorphSet {
  constructor(bundle) {
    this.meta = bundle.header.targets;
    this.data = {};
    for (const [name, t] of Object.entries(this.meta)) {
      this.data[name] = { idx: bundle.block(t.idx), delta: bundle.block(t.delta) };
    }
    this.active = new Map();          // name -> weight
  }

  has(name) { return !!this.data[name]; }

  clear() { this.active.clear(); }

  add(name, w) {
    if (!w || Math.abs(w) < 1e-4) return;
    const t = this.data[name];
    if (!t) { if (!this._warned?.has(name)) (this._warned ||= new Set()).add(name), console.warn('no target', name); return; }
    this.active.set(name, (this.active.get(name) || 0) + w);
  }

  /* apply the active set on top of `base`, writing into `out` */
  apply(base, out) {
    out.set(base);
    for (const [name, w] of this.active) {
      const t = this.data[name];
      const { idx, delta } = t;
      const n = idx.length;
      for (let i = 0; i < n; i++) {
        const v = idx[i] * 3, d = i * 3;
        out[v]     += delta[d]     * w;
        out[v + 1] += delta[d + 1] * w;
        out[v + 2] += delta[d + 2] * w;
      }
    }
  }
}

/* ---------------------------------------------------------------------------
   MakeHuman splits a 0..1 macro slider across three sculpts: the low one, the
   middle one and the high one. Below the midpoint you are blending low->middle,
   above it middle->high. Multiplying two of these gives the nine-way blend that
   muscle and weight need.
   --------------------------------------------------------------------------- */
export function triWeights(v) {
  v = v < 0 ? 0 : v > 1 ? 1 : v;
  if (v < 0.5) return [1 - v * 2, v * 2, 0];
  return [0, 2 - v * 2, v * 2 - 1];
}

/* A 0..1 slider where 0.5 means "leave it alone": returns the signed amount
   and which of the two sculpts to pull on. */
export function biPolar(v) {
  return (v - 0.5) * 2;
}

/* Feed a signed -1..1 amount to a decr/incr pair. */
export function addPair(morph, base, amount, scale = 1) {
  if (amount > 0) morph.add(base + '-incr', amount * scale);
  else if (amount < 0) morph.add(base + '-decr', -amount * scale);
}
